resources:
  containers:
  - container: mtb231
    image: vmmedvid/modustoolbox-cmake:mtb231

trigger:
- master

pr:
- master

jobs:
- job: linux_gcc
  pool:
    vmImage: 'ubuntu-20.04'
  container: mtb231
  steps:
  - task: Bash@3
    inputs:
      filePath: ci/build-all.sh
      arguments: --toolchain GCC
    env:
      CMAKE_GIT_SHALLOW: ON
